#!/usr/bin/env python
import argparse
import logging
import os

from ricecooker.chefs import LineCook
from ricecooker.config import LOGGER


# LOGGING SETTINGS
################################################################################
logging.getLogger("cachecontrol.controller").setLevel(logging.WARNING)
logging.getLogger("requests.packages").setLevel(logging.WARNING)
LOGGER.setLevel(logging.DEBUG)



# BETTER WORLD ED LINE COOK
################################################################################

class BetterWorldEdChef(LineCook):
    """
    Sushi chef for uploading the Better World Ed content folders generated by `souschef.py`.
    """
    pass  # no custom code needed, just using generic `LineCook`


# CLI
################################################################################

if __name__ == '__main__':
    chef = BetterWorldEdChef()
    chef.main()
